################################################################
# Custom site configuration
################################################################

url: http://dalewriting.dale.emery.name
title: dalewriting
subtitle: dale.emery learns to write
disqus_short_name: dalewriting
copyright_prefix: 2003&#8211;
google_analytics_tracking_id:
